on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - macos-15-intel
          - windows-latest
        node_version:
          - 20
          - 24
    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm install
      - run: npm test
      - name: Package and Install
        shell: bash
        run: |
          npm pack
          mkdir ~/package_install
          cp xxhash-addon-*.tgz ~/package_install
          cd ~/package_install
          npm install xxhash-addon-*.tgz

  sanitizers:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - macos-15-intel
        node_version:
          - 24
    env:
      CC: clang
      CXX: clang
      DEBUG: 1
    name: Sanitizers Node ${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Compiler info
        run: clang --version

      - run: npm run debug:build

      - name: Run tests under sanitizers (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: LD_PRELOAD=$(clang -print-file-name=libasan.so) ASAN_OPTIONS=detect_leaks=1 LSAN_OPTIONS=suppressions=suppr.lsan node xxhash-addon.test.js
      - name: Run benchmark under sanitizers (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: LD_PRELOAD=$(clang -print-file-name=libasan.so) ASAN_OPTIONS=detect_leaks=1 LSAN_OPTIONS=suppressions=suppr.lsan node benchmark.js

      - name: Run tests under sanitizers (macOS)
        if: startsWith(matrix.os, 'macos')
        run: DYLD_INSERT_LIBRARIES=$(clang -print-file-name=libclang_rt.asan_osx_dynamic.dylib) node xxhash-addon.test.js
      - name: Run benchmark under sanitizers (macOS)
        if: startsWith(matrix.os, 'macos')
        run: DYLD_INSERT_LIBRARIES=$(clang -print-file-name=libclang_rt.asan_osx_dynamic.dylib) node benchmark.js
